language: node_js
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules

addons:
  ssh_known_hosts: $TARGET_IP

before_install:
- openssl aes-256-cbc -K $encrypted_6586bb378001_key -iv $encrypted_6586bb378001_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- git config user.name $GIT_USERNAME
- git config user.mail $GIT_EMAIL

install:
- true

script:
- true

after_success:
- ls -al ~/.ssh
- chmod 600 ~/.ssh/id_rsa
- ssh root@$TARGET_IP -o StrictHostKeyChecking=no  'cd /www/posts && git pull origin master && hexo clean && hexo g && exit 0'