language: node_js
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: $TARGET_IP
before_install:
- openssl aes-256-cbc -K $encrypted_dde9f8ce7d8f_key -iv $encrypted_dde9f8ce7d8f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- git config user.name $GIT_USERNAME
- git config user.mail $GIT_EMAIL
- echo -e "Host $TARGET_IP StrictHostKeyChecking no" >> ~/.ssh/config
- npm install -g cnpm --registry=https://registry.npm.taobao.org
- cnpm install hexo-cli
install:
- cnpm install
script:
- hexo g
after_success:
- ls -al ~/.ssh
- chmod 600 ~/.ssh/id_rsa
- tar -zcf public.tar.gz ./public
- ssh root@$TARGET_IP -o StrictHostKeyChecking=no 'exit 0'
- scp public.tar.gz root@$TARGET_IP:/www/posts
# - ssh root@$TARGET_IP -o StrictHostKeyChecking=no  'cd /www/posts && git pull origin
#   master && hexo clean && hexo g && exit 0'
- ssh root@$TARGET_IP -o StrictHostKeyChecking=no  'cd /www/posts && hexo clean && tar -xzf public.tar.gz && rm -rf public.tar.gz  && exit 0'
