
# html lang
language: en

# main menu navigation
menu:
  首页: ../
  文章列表: /
  关于我们: /about
  联系我们: /contact



search: false
# avatar: http://olnzpdi2u.bkt.clouddn.com/avatar.jpg
aside-description: aside-description

links:
  百度: https://www.baidu.com/
  谷歌: https://www.google.com/
  知乎: https://www.zhihu.com/

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/script.js
